-- Drop tables if they exist
DROP TABLE IF EXISTS ElectricityUtilities;
DROP TABLE IF EXISTS Utilities;
DROP TABLE IF EXISTS Usages;
DROP TABLE IF EXISTS LampProducts;
DROP TABLE IF EXISTS Products;
DROP TABLE IF EXISTS Owners;
DROP TABLE IF EXISTS Users;